---
- name: Write a simple file
  hosts: vm
  gather_facts: false
  tasks:
    - name: Write file test.txt to temp directory
      ansible.builtin.lineinfile:
        path: /tmp/test.txt
        line: just a quick and easy test
        create: true
